# safe eyes is a break reminder tool
#exec-once=flatpak run io.github.slgobinath.SafeEyes

# pomodoro timer
exec-once= ~/.local/bin/Tools/hypr/hypr-pomodoro-timer.sh 25 5

# nightmode
exec-once = wlsunset -l 16.5 -L 81.5


# tmux session server
exec-once = tmux start-server
