# televison cheet sheet
windowrule {
    name = floating_popup
    match:class = floating_center_1by5
    float = on
    size = 800 500
    center = on
    pin = on
}

# satty screenshot tool
windowrule {
    name = satty_screenshot
    match:class = .*satty.*
    float = on
    size = 1425 800
    center = on
    rounding = 12
}

windowrulev = fullscreen, class:(steam)
windowrulev =  fullscreen, class:(steam)
