# foot config: .config/foot/foot.ini
[main]
font=Hack Nerd Font Mono:size=14
#pad=15x15  # This adds nice internal padding so text isn't touching the edges

# ====== BINDINGS ==========
[key-bindings]
clipboard-copy=Control+c XF86Copy
clipboard-paste=Control+v XF86Paste

[search-bindings]
cancel=Control+g Control+Shift+c 

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape



# ========= THEME ===========
[colors]
foreground=cdd6f4 # Text
background=1e1e2e # Base
regular0=45475a   # Surface 1
regular1=f38ba8   # Red
regular2=a6e3a1   # Green
regular3=f9e2af   # Yellow
regular4=89b4fa   # Blue
regular5=f5c2e7   # Pink
regular6=94e2d5   # Teal
regular7=bac2de   # Subtext 1

# cursor theme
selection-foreground=1e1e2e  # This is the text color inside the cursor
selection-background=f5c2e7  # This is the cursor box color (Pink in Mocha)



# ========= cursor =========
[cursor]
style=block
blink=yes



