# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D0D2DA
background         #19191C
cursor             #767782

active_tab_foreground     #19191C
active_tab_background     #D0D2DA
inactive_tab_foreground   #D0D2DA
inactive_tab_background   #19191C

active_border_color   #D0D2DA
inactive_border_color #19191C
bell_border_color     #12121D

color0      #404043
color1		#12121D
color2		#151520
color3		#313341
color4		#404251
color5		#434555
color6		#5B5F70
color7		#B4B6C2
color8		#7E7F87
color9		#181826
color10		#1C1C2B
color11		#424457
color12		#55586C
color13		#595C71
color14		#797E95
color15		#B4B6C2
