# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8F1DE
background         #201F1F
cursor             #8F8A81

active_tab_foreground     #201F1F
active_tab_background     #F8F1DE
inactive_tab_foreground   #F8F1DE
inactive_tab_background   #201F1F

active_border_color   #F8F1DE
inactive_border_color #201F1F
bell_border_color     #191719

color0      #464546
color1		#191719
color2		#1C1A1C
color3		#444337
color4		#626E58
color5		#AC623C
color6		#B0A278
color7		#ECE3C7
color8		#A59F8B
color9		#221E21
color10		#252325
color11		#5B5949
color12		#829375
color13		#E58250
color14		#EAD8A0
color15		#ECE3C7
