# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8D0E4
background         #1B151F
cursor             #8C86D4

active_tab_foreground     #1B151F
active_tab_background     #F8D0E4
inactive_tab_foreground   #F8D0E4
inactive_tab_background   #1B151F

active_border_color   #F8D0E4
inactive_border_color #1B151F
bell_border_color     #240B33

color0      #423C47
color1		#240B33
color2		#172C94
color3		#79103F
color4		#663059
color5		#9E507A
color6		#B05B85
color7		#EDB4D0
color8		#A67E91
color9		#300E44
color10		#1F3BC5
color11		#A11554
color12		#874077
color13		#D26BA2
color14		#EB79B1
color15		#EDB4D0
