# ~/.config/yazi/yazi.toml

[opener]
edit = [
    { run = 'nvim %s', block = true, desc = "NeoVim" }
]

image = [
    { run = 'imv %s', orphan = true, desc = "imv" }
]

play = [
    { run = 'mpv %s', orphan = true, desc = "mpv" }
]

pdf = [
    { run = '/home/soul/.local/bin/zathura %s', orphan = true, desc = "Zathura" }
]

system_default = [
    { run = 'xdg-open %s', orphan = true, desc = "System Default" }
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/{json,yaml,x-shellscript,javascript,xml}", use = "edit" },
    { url = "*.{sh,py,tf,conf,toml,md}", use = "edit" },
    { mime = "image/*", use = "image" },
    { mime = "{audio,video}/*", use = "play" },
    { mime = "application/pdf", use = "pdf" },
    { url = "*", use = "system_default" }
]

