# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6F7D1
background         #17181A
cursor             #B9BBAA

active_tab_foreground     #17181A
active_tab_background     #F6F7D1
inactive_tab_foreground   #F6F7D1
inactive_tab_background   #17181A

active_border_color   #F6F7D1
inactive_border_color #17181A
bell_border_color     #4D4E41

color0      #3E3E41
color1		#4D4E41
color2		#5D5F62
color3		#767746
color4		#9D9D67
color5		#9B9DA0
color6		#ADAE5C
color7		#EAEBB5
color8		#A4A57E
color9		#666857
color10		#7C7F83
color11		#9D9E5E
color12		#D1D189
color13		#CED2D5
color14		#E7E87B
color15		#EAEBB5
