# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DBEBEB
background         #242528
cursor             #92A5AD

active_tab_foreground     #242528
active_tab_background     #DBEBEB
inactive_tab_foreground   #DBEBEB
inactive_tab_background   #242528

active_border_color   #DBEBEB
inactive_border_color #242528
bell_border_color     #283A44

color0      #494B4E
color1		#283A44
color2		#374754
color3		#465761
color4		#455A5F
color5		#526A76
color6		#729494
color7		#C3DADA
color8		#899899
color9		#364D5B
color10		#495E6F
color11		#5E7481
color12		#5C777E
color13		#6D8E9D
color14		#98C5C6
color15		#C3DADA
