# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FCF6F4
background         #07000A
cursor             #FBC4F9

active_tab_foreground     #07000A
active_tab_background     #FCF6F4
inactive_tab_foreground   #FCF6F4
inactive_tab_background   #07000A

active_border_color   #FCF6F4
inactive_border_color #07000A
bell_border_color     #99828B

color0      #07000A
color1		#99828B
color2		#BB6EBE
color3		#8D92BC
color4		#B2998A
color5		#A0AABB
color6		#B8ACA8
color7		#F2E9E7
color8		#A9A3A2
color9		#CCADB9
color10		#FA92FE
color11		#BCC3FA
color12		#EECCB7
color13		#D6E2FA
color14		#F5E5E0
color15		#F2E9E7
