[dmenu]
dmenu_command = rofi -dmenu -i -p "Networks" -theme ~/.config/rofi/themes/KooL_Catppuccin_mocha.rasi
list_saved = True
active_chars = ➜
wifi_chars = 󰤯 󰤟 󰤢 󰤥
format = {name}  {sec}  {bars}

[editor]
terminal = foot
gui_if_available = True

[nmdm]
# Wait 5 seconds before re-opening after a manual rescan
rescan_delay = 5
