[dmenu]
# Use rofi with a custom theme and case-insensitive search
dmenu_command = rofi -dmenu -i -p "Networks" -theme ~/.config/rofi/themes/KooL_style-14_column-1.rasi
list_saved = True
active_chars = ➜
wifi_chars = 󰤯 󰤟 󰤢 󰤥
# Remove {icon} if it exists
format = {name}  {sec}  {bars}

[editor]
# Use a terminal you have installed (e.g., kitty, alacritty, or foot)
terminal = foot
gui_if_available = True

[nmdm]
# Wait 5 seconds before re-opening after a manual rescan
rescan_delay = 5
