# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(201F1F)
$foreground = rgb(F8F1DE)
$color0 = rgb(464546)
$color1 = rgb(191719)
$color2 = rgb(1C1A1C)
$color3 = rgb(444337)
$color4 = rgb(626E58)
$color5 = rgb(AC623C)
$color6 = rgb(B0A278)
$color7 = rgb(ECE3C7)
$color8 = rgb(A59F8B)
$color9 = rgb(221E21)
$color10 = rgb(252325)
$color11 = rgb(5B5949)
$color12 = rgb(829375)
$color13 = rgb(E58250)
$color14 = rgb(EAD8A0)
$color15 = rgb(ECE3C7)
