# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000004)
$foreground = rgb(D7E9EB)
$color0 = rgb(000004)
$color1 = rgb(4B6583)
$color2 = rgb(4D6784)
$color3 = rgb(8E5F6E)
$color4 = rgb(698D94)
$color5 = rgb(7A8F69)
$color6 = rgb(6B9095)
$color7 = rgb(BED7DB)
$color8 = rgb(859799)
$color9 = rgb(6486AE)
$color10 = rgb(678AB0)
$color11 = rgb(BD7E93)
$color12 = rgb(8BBCC5)
$color13 = rgb(A3BE8C)
$color14 = rgb(8EC0C7)
$color15 = rgb(BED7DB)
