# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131111)
$foreground = rgb(FDF9F5)
$color0 = rgb(3B3939)
$color1 = rgb(BD7D71)
$color2 = rgb(BE8072)
$color3 = rgb(BF8073)
$color4 = rgb(B4AAA1)
$color5 = rgb(B9ADA5)
$color6 = rgb(BCB2A9)
$color7 = rgb(F4EEE8)
$color8 = rgb(ABA6A2)
$color9 = rgb(FCA796)
$color10 = rgb(FEAA98)
$color11 = rgb(FEAB99)
$color12 = rgb(F0E3D7)
$color13 = rgb(F6E7DC)
$color14 = rgb(FBEDE2)
$color15 = rgb(F4EEE8)
